#!/usr/bin/env bash
PWD=`pwd`
python3 -m venv .venv
echo $PWD
activate () {
    . $PWD/.venv/bin/activate
}
activate
pip install -r requirements.txt
export AWS_SHARED_CREDENTIALS_FILE="$(pwd)/../.aws/credentials"
export AWS_DEFAULT_REGION=us-west-2
export FLASK_APP=flask_api
export FLASK_ENV=development
python3 -m flask run